// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ProjectInsights.Data;

#nullable disable

namespace ProjectInsights.Migrations
{
    [DbContext(typeof(ProjectInsightsDbContext))]
    [Migration("20251223224142_AddUniquePrNumberConstraint")]
    partial class AddUniquePrNumberConstraint
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ProjectInsights.Data.Entities.AnalysisRun", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("BaseBranch")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("base_branch");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_date");

                    b.Property<string>("GitHubOwner")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("github_owner");

                    b.Property<string>("GitHubRepo")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("github_repo");

                    b.Property<int>("PrCount")
                        .HasColumnType("integer")
                        .HasColumnName("pr_count");

                    b.Property<DateTime>("RunDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("run_date");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_date");

                    b.HasKey("Id");

                    b.ToTable("analysis_runs", (string)null);
                });

            modelBuilder.Entity("ProjectInsights.Data.Entities.DailyProjectStats", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<DateOnly>("Day")
                        .HasColumnType("date")
                        .HasColumnName("day");

                    b.Property<int>("FilesAdded")
                        .HasColumnType("integer")
                        .HasColumnName("files_added");

                    b.Property<int>("FilesModified")
                        .HasColumnType("integer")
                        .HasColumnName("files_modified");

                    b.Property<int>("PrCount")
                        .HasColumnType("integer")
                        .HasColumnName("pr_count");

                    b.Property<string>("ProjectGroup")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("project_group");

                    b.Property<string>("ProjectName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("project_name");

                    b.Property<int>("TotalLinesChanged")
                        .HasColumnType("integer")
                        .HasColumnName("total_lines_changed");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("NOW()");

                    b.HasKey("Id");

                    b.HasIndex("Day");

                    b.HasIndex("ProjectGroup");

                    b.HasIndex("Day", "ProjectName")
                        .IsUnique();

                    b.ToTable("daily_project_stats", (string)null);
                });

            modelBuilder.Entity("ProjectInsights.Data.Entities.DailyTeamProjectStats", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<DateOnly>("Day")
                        .HasColumnType("date")
                        .HasColumnName("day");

                    b.Property<int>("PrCount")
                        .HasColumnType("integer")
                        .HasColumnName("pr_count");

                    b.Property<string>("ProjectGroup")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("project_group");

                    b.Property<string>("ProjectName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("project_name");

                    b.Property<string>("TeamName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("team_name");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("NOW()");

                    b.HasKey("Id");

                    b.HasIndex("Day");

                    b.HasIndex("ProjectGroup");

                    b.HasIndex("TeamName");

                    b.HasIndex("Day", "ProjectName", "TeamName")
                        .IsUnique();

                    b.ToTable("daily_team_project_stats", (string)null);
                });

            modelBuilder.Entity("ProjectInsights.Data.Entities.PrFile", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("Additions")
                        .HasColumnType("integer")
                        .HasColumnName("additions");

                    b.Property<int>("Changes")
                        .HasColumnType("integer")
                        .HasColumnName("changes");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<int>("Deletions")
                        .HasColumnType("integer")
                        .HasColumnName("deletions");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("file_name");

                    b.Property<string>("ProjectGroup")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("project_group");

                    b.Property<string>("ProjectName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("project_name");

                    b.Property<long>("PullRequestId")
                        .HasColumnType("bigint")
                        .HasColumnName("pull_request_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("ProjectGroup");

                    b.HasIndex("ProjectName");

                    b.HasIndex("PullRequestId");

                    b.ToTable("pr_files", (string)null);
                });

            modelBuilder.Entity("ProjectInsights.Data.Entities.PrProject", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<int>("FileCount")
                        .HasColumnType("integer")
                        .HasColumnName("file_count");

                    b.Property<string>("ProjectGroup")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("project_group");

                    b.Property<string>("ProjectName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("project_name");

                    b.Property<long>("PullRequestId")
                        .HasColumnType("bigint")
                        .HasColumnName("pull_request_id");

                    b.HasKey("Id");

                    b.HasIndex("PullRequestId", "ProjectName")
                        .IsUnique();

                    b.ToTable("pr_projects", (string)null);
                });

            modelBuilder.Entity("ProjectInsights.Data.Entities.PullRequest", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("AnalysisRunId")
                        .HasColumnType("bigint")
                        .HasColumnName("analysis_run_id");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("author");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<bool>("IsRollupPr")
                        .HasColumnType("boolean")
                        .HasColumnName("is_rollup_pr");

                    b.Property<string>("MergeCommitSha")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("merge_commit_sha");

                    b.Property<DateTime>("MergedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("merged_at");

                    b.Property<int>("PrNumber")
                        .HasColumnType("integer")
                        .HasColumnName("pr_number");

                    b.Property<string>("Team")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("team");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.HasKey("Id");

                    b.HasIndex("AnalysisRunId");

                    b.HasIndex("PrNumber")
                        .IsUnique();

                    b.ToTable("pull_requests", (string)null);
                });

            modelBuilder.Entity("ProjectInsights.Data.Entities.PrFile", b =>
                {
                    b.HasOne("ProjectInsights.Data.Entities.PullRequest", "PullRequest")
                        .WithMany("PrFiles")
                        .HasForeignKey("PullRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PullRequest");
                });

            modelBuilder.Entity("ProjectInsights.Data.Entities.PrProject", b =>
                {
                    b.HasOne("ProjectInsights.Data.Entities.PullRequest", "PullRequest")
                        .WithMany("PrProjects")
                        .HasForeignKey("PullRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PullRequest");
                });

            modelBuilder.Entity("ProjectInsights.Data.Entities.PullRequest", b =>
                {
                    b.HasOne("ProjectInsights.Data.Entities.AnalysisRun", "AnalysisRun")
                        .WithMany("PullRequests")
                        .HasForeignKey("AnalysisRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AnalysisRun");
                });

            modelBuilder.Entity("ProjectInsights.Data.Entities.AnalysisRun", b =>
                {
                    b.Navigation("PullRequests");
                });

            modelBuilder.Entity("ProjectInsights.Data.Entities.PullRequest", b =>
                {
                    b.Navigation("PrFiles");

                    b.Navigation("PrProjects");
                });
#pragma warning restore 612, 618
        }
    }
}
